FORMAT: 1A
HOST: http://localhost:2701

# Icon Finder RESTAPI - Kevin Fericco

RESTAPI of Icon information such as :
- Data about icon at icon finder

# Group Authentication
The Iconfinder API uses API keys to authenticate the requests. You can create an application and manage your API keys under your account settings. The API key should be sent as an HTTP header with every request in the format
```Authorization : Bearer {token}```
